server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: jogosRoute
          uri: lb://JOGOS
          predicates: 
            - Path=/jogos/**
        - id: bibliotecaRoute
          uri: ld://BIBLIOTECA
          predicates:
            - Path=/biblioteca/**
