server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: movieRoute
          uri: lb://MOVIE
          predicates: 
            - Path=/movie/**
        - id: catalogRoute
          uri: ld://CATALOG
          predicates:
            - Path=/catalog/**
