server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: catalogRoute
          uri: lb://CATALOG
          predicates: 
            - Path=/catalog/**
        - id: movieRoute
          uri: ld://MOVIE
          predicates:
            - Path=/movie/**
