server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: catalogRoute
          uri: lb://ctalog
          predicates: 
            - Path=/catalog/**
        - id: movieRoute
          uri: ld://movie
          predicates:
            - Path=/movie/**
